---
title: "Introduction"
author: "Mark Hagemann"
date: "November 13, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

The upcoming launch of the Surface Water and Ocean Topography (SWOT) satellite mission has spawned vigorous efforts to develop methods for mapping remotely sensed observations of river geometry into accurate estimates of discharge. A major objective has been to estimate discharge (Q) using measurements of stream width (W), slope (S) and height (H) at multiple locations within a stream reach. Multiple methodologies have been put forward and tested, with varying degrees of success. Overall, however, the performance of these methodologies has fallen short of expectations [@Durand2016]. 

The emergent paradigm--termed McFLI for Mass-conserved Flow Law Inversion--relies on two physical constraints: conservation of mass at the reach scale, and hydraulic flow laws such as Manning's equation and At-Many-Stations Hydraulic Geometry (AMHG). As analytic approaches to solving McFLI have not been fruitful, other approaches including hueristic optimization and Bayesian inference have been employed. These have the benefit of yielding estimates of quantities of interest, including discharge and flow-law parameters, but they do so at the expense of obscuring much of the inferential machinery. 
The purpose of this document is to remove some of the intrigue surrounding Bayesian flow-law inversion and McFLI more generally. In it, I shall address the underlying premise of McFLI--that remote-sensed observations contain sufficient information to infer discharge and/or flow-law parameters using remote-sensed observations alone. This will serve to diagnose many of the shortcomings observed in McFLI performance to date, as well as to perscribe additional data and modeling needs in order for McFLI to reach its full potential.


## Orverview of McFLI

McFLI [@Gleason2017] represents a combination of well-established physical equations in a way that is amenible to satellite remote sensing. Given in-situ data, a hydrologist may work out the parameters of, say, Manning's equation that map stream width, slope, and cross-sectional area to velocity or discharge, thereby giving a precisely constrained approximation of stream hydraulics for that location. Lacking such in-situ data--in particular discharge measurement--remote-sensing applications of flow-laws remain underconstrained. Unlike previous applications of remotely sensed observations to discharge estimation [e.g. ####], McFLI is targeted primarily at ungaged basins in which the amount of existing hydraulic information is potentially zero. This lack of in-situ data puts McFLI at a serious disadvantage over gage-assisted discharge estimation. However, unlike in-situ gauge measurements, satellite observations can be made with arbitrarily high spatial resolution, allowing them to be combined via conservation of mass at suitably short (< ~10 km, non-branching) reaches. 

SWOT will provide measurements of stream geometry indexed in time (across overpasses of the SWOT satellite), as well as space (multiple locations within a single river). These observations are stream width, $W_{it}$, slope, $S_{it}$, and height, $H_{it}$, where the indices $i = 1, \dots N_i$ and $t = 1, \dots, N_t$ indicate the location and time, respectively, of each observation. Cross-sectional area, $A_{it}$ can be partially measured by integrating width over height; however, there will always remain an unobservable portion, $A_{0, i}$ of each cross section's area that cannot be observed. The remaining--observable--portion, $\delta A_{it}$, is obtained by the sum:


$$
\delta A_{it} = \sum_{t' : W_{t'} \leq W_t}W_{t'}\Delta H_{t'}
$$
where $\Delta H_{t'}$ is the height difference from the height at the next-smallest width. Thus, $A_{it} = A_{0, i} + \delta A_{it}$, concentrating the uncertainty about $A_{it}$ in the unobserved but temporally invariant $A_{0, i}$. In many if not all McFLI applications the only unknowns are temporally invariant quantities like $A_{0, i}$, spatially invariant quantities like $Q_t$, and globally invariant parameters like Manning's $n$. 

At least on the face of it, this leaves McFLI with only time-invariant and/or space-invariant unknowns; all quantities that are variable in both time and space are observed. Furthermore we can often define McFLI to be of arbitrarily high spatial and temporal resolution, meaning that the number of observations $N_iN_t$ is much larger than the number of unknowns, which is on the order of $N_i + N_t$. If this is the case, then why has discharge retrieval uwing McFLI proven so difficult? Is it possible to fully obtain discharge estimates from SWOT measurements alone? If not, what information about discharge and flow-law parameters can be obtained from SWOT data?

The remainder of this document is structured as follows. Section #### draws analogues between simplified versions of Manning's McFLI and common analysis of variance (ANOVA) models, and using linear model theory places bounds on what can and cannot be estimated using SWOT observations. Section #### further elucidates the identifiable McFLI parameters using probability, likelihood, and Bayesian theory. Section #### illustrates the estimation of one McFLI parameter, $A_0$, using in-situ measured, model-derived, and synthetic datasets. Finally, section #### concludes with a discussion of these findings along with a prognosis of where they may lead.
